---
language: perl
  - "5.18.2"
  - "5.16.3"

env:
  - SITE=playbook.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install curl -y

install:
  - pip install -U ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i ci/inventory ci/$SITE --syntax-check"

  # Run the ansible ci playbook
  - "ansible-playbook -i ci/inventory ci/playbook.yml -c local -f 10 -vvvv"

  # Additional external test script to run, output a version or fail
  # - "echo 'this script says hi'"
