---

- name: Update apt cache
  apt: update_cache=yes
  tags: bootstrap

- name: Apt install required system packages.
  apt: pkg={{item}} state=installed
  tags: bootstrap
  with_items:
    - curl
    - git
    - libssl-dev

- include: common.yml
